### PR TITLE
add ARNIQA

### PR DESCRIPTION
**Pull request by LorenzoAgnolucci**
Add implementation of [ARNIQA](https://arxiv.org/abs/2310.14918)

### CODE REVIEW

**Comment by chaofengc** [comment]
Thank you so much for your contribution 🤗 !

**Comment by LorenzoAgnolucci** [comment]
Hi @chaofengc!

Maybe I am asking too much, but could you please add a note about the addition of ARNIQA to the repo in the **Updates/Changelog** section of the README? Similar to what did for UNIQUE on March 11, 2024. I think it would give ARNIQA more visibility, otherwise its addition could be overlooked.

Thanks in advance and sorry if I am asking too much.

**Comment by chaofengc** [comment]
Sure, I am glad to do so!

**Comment by LorenzoAgnolucci** [comment]
Thank you very much!

**Pull request merged**
